In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
import numpy as np
from matpower import start_instance

from matpowercaseframes import CaseFrames

In [ ]:
def find_inf(df):
    num = df.select_dtypes(include="number")
    mask = np.isinf(num)  # DataFrame mask (same shape as num)
    r, c = np.where(mask.to_numpy())
    hits = list(zip(num.index[r], num.columns[c], num.to_numpy()[r, c]))
    return hits, mask

In [ ]:
m = start_instance()

In [ ]:
CASE_NAME = "case9241pegase.m"
cf_case9241pegase = CaseFrames(CASE_NAME)

In [ ]:
cf_case9241pegase.infer_numpy()  # optional, RuntimeWarning due to inf, expected
cf_case9241pegase.gen

/Users/myasirroni/Documents/Git/matpowercaseframes/env/lib/python3.12/site-packages/pandas/core/dtypes/cast.py:968: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():
/Users/myasirroni/Documents/Git/matpowercaseframes/env/lib/python3.12/site-packages/pandas/core/dtypes/cast.py:995: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN,...,PC2,QC1MIN,QC1MAX,QC2MIN,QC2MAX,RAMP_AGC,RAMP_10,RAMP_30,RAMP_Q,APF
gen,,,,,,,,,,,,,,,,,,,,,
1,2,-81.40,6.64,42.19,-20.45,1.031734,100,1,100.00,-108.53,...,0,0,0,0,0,0,0,0,0,0
2,6,701.00,183.79,524.53,-211.57,1.038476,100,1,1200.00,400.00,...,0,0,0,0,0,0,0,0,0,0
3,8,499.70,-0.95,251.73,-246.25,1.023005,100,1,524.68,0.00,...,0,0,0,0,0,0,0,0,0,0
4,18,467.50,201.91,212.97,-93.48,1.026728,100,1,500.00,166.67,...,0,0,0,0,0,0,0,0,0,0
5,25,319.60,164.04,179.43,-66.21,1.028526,100,1,400.00,0.00,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,9215,4.77,3.71,18.19,-6.61,1.008696,100,1,40.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1442,9230,-126.70,47.40,127.96,-55.88,1.027519,100,1,100.00,-168.93,...,0,0,0,0,0,0,0,0,0,0
1443,9235,353.39,124.55,176.33,-72.95,1.041140,100,1,400.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1444,9238,829.80,16.82,552.08,-183.99,1.097633,100,1,1200.00,400.00,...,0,0,0,0,0,0,0,0,0,0
1445,9239,419.00,107.54,274.20,-93.22,1.017601,100,1,600.00,200.00,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
hits, mask = find_inf(cf_case9241pegase.gen)
cf_case9241pegase.gen.loc[mask.any(axis=1)]

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN,...,PC2,QC1MIN,QC1MAX,QC2MIN,QC2MAX,RAMP_AGC,RAMP_10,RAMP_30,RAMP_Q,APF
gen,,,,,,,,,,,,,,,,,,,,,
45,310,346.18,632.57,inf,-inf,1.155322,100,1,700.00,200.00,...,0,0,0,0,0,0,0,0,0,0
276,1776,595.00,-773.19,inf,-inf,0.967759,100,1,624.75,0.00,...,0,0,0,0,0,0,0,0,0,0
537,3335,-600.00,1825.38,inf,-inf,1.080640,100,1,630.00,-630.00,...,0,0,0,0,0,0,0,0,0,0
695,4231,2641.24,604.18,inf,-inf,1.042866,100,1,4188.95,1333.33,...,0,0,0,0,0,0,0,0,0,0
848,5239,-1344.40,-125.88,inf,-inf,0.990479,100,1,100.00,-1792.53,...,0,0,0,0,0,0,0,0,0,0
1274,8109,992.00,834.95,inf,-inf,1.059636,100,1,1041.60,0.00,...,0,0,0,0,0,0,0,0,0,0
1334,8532,-697.25,-741.74,inf,-inf,1.032486,100,1,100.00,-929.67,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
CASE_NAME = "case9241pegase.m"
cf_case9241pegase_lc = CaseFrames(CASE_NAME, load_case_engine=m)

In [ ]:
cf_case9241pegase.infer_numpy()  # optional, RuntimeWarning due to inf, expected
cf_case9241pegase.gen

/Users/myasirroni/Documents/Git/matpowercaseframes/env/lib/python3.12/site-packages/pandas/core/dtypes/cast.py:968: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():
/Users/myasirroni/Documents/Git/matpowercaseframes/env/lib/python3.12/site-packages/pandas/core/dtypes/cast.py:995: RuntimeWarning: invalid value encountered in cast
  elif (arr.astype(int) == arr).all():

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN,...,PC2,QC1MIN,QC1MAX,QC2MIN,QC2MAX,RAMP_AGC,RAMP_10,RAMP_30,RAMP_Q,APF
gen,,,,,,,,,,,,,,,,,,,,,
1,2,-81.40,6.64,42.19,-20.45,1.031734,100,1,100.00,-108.53,...,0,0,0,0,0,0,0,0,0,0
2,6,701.00,183.79,524.53,-211.57,1.038476,100,1,1200.00,400.00,...,0,0,0,0,0,0,0,0,0,0
3,8,499.70,-0.95,251.73,-246.25,1.023005,100,1,524.68,0.00,...,0,0,0,0,0,0,0,0,0,0
4,18,467.50,201.91,212.97,-93.48,1.026728,100,1,500.00,166.67,...,0,0,0,0,0,0,0,0,0,0
5,25,319.60,164.04,179.43,-66.21,1.028526,100,1,400.00,0.00,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,9215,4.77,3.71,18.19,-6.61,1.008696,100,1,40.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1442,9230,-126.70,47.40,127.96,-55.88,1.027519,100,1,100.00,-168.93,...,0,0,0,0,0,0,0,0,0,0
1443,9235,353.39,124.55,176.33,-72.95,1.041140,100,1,400.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1444,9238,829.80,16.82,552.08,-183.99,1.097633,100,1,1200.00,400.00,...,0,0,0,0,0,0,0,0,0,0
1445,9239,419.00,107.54,274.20,-93.22,1.017601,100,1,600.00,200.00,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
hits, mask = find_inf(cf_case9241pegase.gen)
cf_case9241pegase.gen.loc[mask.any(axis=1)]

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN,...,PC2,QC1MIN,QC1MAX,QC2MIN,QC2MAX,RAMP_AGC,RAMP_10,RAMP_30,RAMP_Q,APF
gen,,,,,,,,,,,,,,,,,,,,,
45,310,346.18,632.57,inf,-inf,1.155322,100,1,700.00,200.00,...,0,0,0,0,0,0,0,0,0,0
276,1776,595.00,-773.19,inf,-inf,0.967759,100,1,624.75,0.00,...,0,0,0,0,0,0,0,0,0,0
537,3335,-600.00,1825.38,inf,-inf,1.080640,100,1,630.00,-630.00,...,0,0,0,0,0,0,0,0,0,0
695,4231,2641.24,604.18,inf,-inf,1.042866,100,1,4188.95,1333.33,...,0,0,0,0,0,0,0,0,0,0
848,5239,-1344.40,-125.88,inf,-inf,0.990479,100,1,100.00,-1792.53,...,0,0,0,0,0,0,0,0,0,0
1274,8109,992.00,834.95,inf,-inf,1.059636,100,1,1041.60,0.00,...,0,0,0,0,0,0,0,0,0,0
1334,8532,-697.25,-741.74,inf,-inf,1.032486,100,1,100.00,-929.67,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
mpc = cf_case9241pegase.to_mpc()
_ = m.runpf(mpc)

In [ ]:
mpc = cf_case9241pegase_lc.to_mpc()
_ = m.runpf(mpc)

In [ ]:
for attr in cf_case9241pegase.attributes:
    display(attr, getattr(cf_case9241pegase, attr))

'version'

'2'

'baseMVA'

100

'bus'

,BUS_I,BUS_TYPE,PD,QD,GS,BS,BUS_AREA,VM,VA,BASE_KV,ZONE,VMAX,VMIN
bus,,,,,,,,,,,,,
1,1,1,378.40,98.5,0.0,16.61,0,1.007206,-36.856998,220,6,1.1,0.9
2,2,2,0.00,0.0,0.0,0.00,0,1.031734,-12.028001,154,1,1.1,0.9
3,3,1,151.00,48.8,0.0,4.69,0,1.017843,-21.794234,220,5,1.1,0.9
4,4,1,171.41,23.4,0.0,2.10,0,1.020147,-7.224254,220,5,1.1,0.9
5,5,1,45.95,14.0,0.0,13.34,0,0.989775,-49.871783,220,6,1.1,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9237,9237,1,0.00,0.0,0.0,1.27,0,1.047699,-23.228502,110,19,1.1,0.9
9238,9238,2,0.00,0.0,0.0,0.00,0,1.097633,15.484001,380,13,1.3,0.7
9239,9239,2,0.00,0.0,0.0,0.00,0,1.017601,6.125470,380,2,1.1,0.9
9240,9240,1,0.00,0.0,0.0,3.66,0,0.960374,-31.768249,150,9,1.1,0.9
9241,9241,1,0.00,0.0,0.0,0.36,0,1.044245,-9.735227,220,5,1.1,0.9

'gen'

,GEN_BUS,PG,QG,QMAX,QMIN,VG,MBASE,GEN_STATUS,PMAX,PMIN,...,PC2,QC1MIN,QC1MAX,QC2MIN,QC2MAX,RAMP_AGC,RAMP_10,RAMP_30,RAMP_Q,APF
gen,,,,,,,,,,,,,,,,,,,,,
1,2,-81.40,6.64,42.19,-20.45,1.031734,100,1,100.00,-108.53,...,0,0,0,0,0,0,0,0,0,0
2,6,701.00,183.79,524.53,-211.57,1.038476,100,1,1200.00,400.00,...,0,0,0,0,0,0,0,0,0,0
3,8,499.70,-0.95,251.73,-246.25,1.023005,100,1,524.68,0.00,...,0,0,0,0,0,0,0,0,0,0
4,18,467.50,201.91,212.97,-93.48,1.026728,100,1,500.00,166.67,...,0,0,0,0,0,0,0,0,0,0
5,25,319.60,164.04,179.43,-66.21,1.028526,100,1,400.00,0.00,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1441,9215,4.77,3.71,18.19,-6.61,1.008696,100,1,40.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1442,9230,-126.70,47.40,127.96,-55.88,1.027519,100,1,100.00,-168.93,...,0,0,0,0,0,0,0,0,0,0
1443,9235,353.39,124.55,176.33,-72.95,1.041140,100,1,400.00,0.00,...,0,0,0,0,0,0,0,0,0,0
1444,9238,829.80,16.82,552.08,-183.99,1.097633,100,1,1200.00,400.00,...,0,0,0,0,0,0,0,0,0,0
1445,9239,419.00,107.54,274.20,-93.22,1.017601,100,1,600.00,200.00,...,0,0,0,0,0,0,0,0,0,0

'branch'

,F_BUS,T_BUS,BR_R,BR_X,BR_B,RATE_A,RATE_B,RATE_C,TAP,SHIFT,BR_STATUS,ANGMIN,ANGMAX
branch,,,,,,,,,,,,,
1,5147,3097,0.000600,0.006160,0,823,0,0,0.000000,0.0,1,-360,360
2,5147,8763,0.000500,0.007400,0,921,0,0,0.000000,0.0,1,-360,360
3,2169,3124,0.001070,0.006260,0,476,0,0,0.000000,0.0,1,-360,360
4,2169,3234,0.000841,0.005500,0,476,0,0,0.000000,0.0,1,-360,360
5,3517,711,0.001430,0.015630,0,1645,0,0,0.000000,0.0,1,-360,360
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16045,3292,3612,0.000000,0.047975,0,0,0,0,0.962181,0.0,1,-360,360
16046,1929,5090,0.000000,0.050500,0,0,0,0,0.950000,0.0,1,-360,360
16047,1929,5090,0.000000,0.050500,0,0,0,0,0.950000,0.0,1,-360,360
16048,1929,5090,0.000000,0.050500,0,0,0,0,0.950000,0.0,1,-360,360
16049,8110,8441,0.000000,0.070313,0,0,0,0,0.950000,0.0,1,-360,360

'gencost'

      MODEL  STARTUP  SHUTDOWN  NCOST  C2  C1  C0
gen
1         2        0         0      3   0   1   0
2         2        0         0      3   0   1   0
3         2        0         0      3   0   1   0
4         2        0         0      3   0   1   0
5         2        0         0      3   0   1   0
...     ...      ...       ...    ...  ..  ..  ..
1441      2        0         0      3   0   1   0
1442      2        0         0      3   0   1   0
1443      2        0         0      3   0   1   0
1444      2        0         0      3   0   1   0
1445      2        0         0      3   0   1   0

[1445 rows x 7 columns]

In [ ]:
m.exit()